### ISSUE TITLE
Link to live site in README.md

### ISSUE THREAD

**Issue by leojclarke** [RuariDouglas/personal-portfolio#1]
You may want to include the hyperlink to your portfolio website in the README.md

CODE: `**[View the live site](https://ruaridouglas.com/)**`

LINK: **[View the live site](https://ruaridouglas.com/)**

**Comment by bokonist** [comment]
Hey Ruari, I was wondering what you used for generating your CV on your website. Didn't want to open a whole another issue just for this. Thanks in advance @RuariDouglas

**Comment by RuariDouglas** [comment]
@leojclarke Thankyou for this Leo, I’ll get on this when I’m back home! 

@bokonist  I just uploaded my CV to google drive, right click on the file and select share, you’ll find a share link there!

**Comment by leojclarke** [comment]
@RuariDouglas awesome! I hope you don't think I'm being facesious 😂 I thought I'd use this GitHub for some social interaction. I found your portfolio from Code Creative's YouTube video and I am in awe! Also love your CV and downloaded that bad boy for some stealage straightaway... Lots of ❤ from a Brit in Germany ✌

**Comment by bokonist** [comment]
@RuariDouglas , yes, I found the google drive CV but i was wondering how you made it, did you use a website to generate it or design it yourself? It looks so clean and beautitful. 

Agree with @leojclarke, great website, I also found your portfolio from the same channel and will be "borrowing" some of your super clean design ideas, cheers 😄

**Comment by RuariDouglas** [comment]
@leojclarke  Not at all! Haha, GitHub, social media for the anti-social! Thankyou so much man, it's crazy hearing all the positive responses, here's me thinking I was bang average the whole time! (The life of a self-taught developer) 😂 Steal away my friend, do you want the Illustrator file? Can send you that if it would help....

@bokonist  Ahhhh apologies, yes I designed it myself! Again, I can send you the Adobe Illustrator file too if you would like? 
The fact that you guys want to 'borrow' the ideas from the CV and portfolio is pretty flattering so please, steal away!...sorry, borrow away!

**Comment by bokonist** [comment]
@RuariDouglas , that would be perfect. Thank you so much, can you add it to the repo or share it to google drive?

**Comment by RuariDouglas** [comment]
@bokonist & @leojclarke  I have added it to the repo, see CV-template.ai. Enjoy! Feel free to connect with me on Linkedin if you have any questions!
